{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "235c929e-3da7-4d71-a7d3-f008f1f98a73",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (2.2.3)\n",
      "Requirement already satisfied: numpy in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (2.2.4)\n",
      "Requirement already satisfied: matplotlib in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (3.10.1)\n",
      "Requirement already satisfied: seaborn in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (0.13.2)\n",
      "Requirement already satisfied: scikit-learn in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (1.6.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from matplotlib) (1.3.1)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from matplotlib) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from matplotlib) (4.57.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from matplotlib) (1.4.8)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from matplotlib) (24.2)\n",
      "Requirement already satisfied: pillow>=8 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from matplotlib) (11.2.1)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from matplotlib) (3.2.3)\n",
      "Requirement already satisfied: scipy>=1.6.0 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from scikit-learn) (1.15.2)\n",
      "Requirement already satisfied: joblib>=1.2.0 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from scikit-learn) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from scikit-learn) (3.6.0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\aqsa shahid\\appdata\\local\\programs\\python\\python313\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install pandas numpy matplotlib seaborn scikit-learn\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "e08a22f0-77cb-48fb-b061-9e095fef9da8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Load dataset (ensure it's in the same folder)\n",
    "bank_df = pd.read_csv(\"bank.csv\")  # Or 'BankMarketing.csv' if that's your file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "bec8d294-b714-413c-841f-a65de325c64e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  age;\"job\";\"marital\";\"education\";\"default\";\"balance\";\"housing\";\"loan\";\"contact\";\"day\";\"month\";\"duration\";\"campaign\";\"pdays\";\"previous\";\"poutcome\";\"y\"\n",
      "0  30;\"unemployed\";\"married\";\"primary\";\"no\";1787;...                                                                                                  \n",
      "1  33;\"services\";\"married\";\"secondary\";\"no\";4789;...                                                                                                  \n",
      "2  35;\"management\";\"single\";\"tertiary\";\"no\";1350;...                                                                                                  \n",
      "3  30;\"management\";\"married\";\"tertiary\";\"no\";1476...                                                                                                  \n",
      "4  59;\"blue-collar\";\"married\";\"secondary\";\"no\";0;...                                                                                                  \n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 4521 entries, 0 to 4520\n",
      "Data columns (total 1 columns):\n",
      " #   Column                                                                                                                                                Non-Null Count  Dtype \n",
      "---  ------                                                                                                                                                --------------  ----- \n",
      " 0   age;\"job\";\"marital\";\"education\";\"default\";\"balance\";\"housing\";\"loan\";\"contact\";\"day\";\"month\";\"duration\";\"campaign\";\"pdays\";\"previous\";\"poutcome\";\"y\"  4521 non-null   object\n",
      "dtypes: object(1)\n",
      "memory usage: 35.4+ KB\n",
      "None\n",
      "       age;\"job\";\"marital\";\"education\";\"default\";\"balance\";\"housing\";\"loan\";\"contact\";\"day\";\"month\";\"duration\";\"campaign\";\"pdays\";\"previous\";\"poutcome\";\"y\"\n",
      "count                                                4521                                                                                                  \n",
      "unique                                               4521                                                                                                  \n",
      "top     44;\"entrepreneur\";\"single\";\"tertiary\";\"no\";113...                                                                                                  \n",
      "freq                                                    1                                                                                                  \n"
     ]
    }
   ],
   "source": [
    "print(bank_df.head())        # Show first 5 rows\n",
    "print(bank_df.info())        # Data types and nulls\n",
    "print(bank_df.describe())    # Summary statistics\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "8f586775-6a21-4e3f-b396-d1f2382f6195",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "age;\"job\";\"marital\";\"education\";\"default\";\"balance\";\"housing\";\"loan\";\"contact\";\"day\";\"month\";\"duration\";\"campaign\";\"pdays\";\"previous\";\"poutcome\";\"y\"    0\n",
      "dtype: int64\n"
     ]
    }
   ],
   "source": [
    "# Check for nulls\n",
    "print(bank_df.isnull().sum())\n",
    "\n",
    "# Drop or fill missing values\n",
    "bank_df.dropna(inplace=True)  # Removes rows with missing values\n",
    "# bank_df.fillna(method='ffill', inplace=True)  # Optional: fill missing values\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "cefe7092-a3ba-4d5f-bf38-7c473e56b869",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['age;\"job\";\"marital\";\"education\";\"default\";\"balance\";\"housing\";\"loan\";\"contact\";\"day\";\"month\";\"duration\";\"campaign\";\"pdays\";\"previous\";\"poutcome\";\"y\"'], dtype='object')\n"
     ]
    }
   ],
   "source": [
    "print(bank_df.columns)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "55244573-a07e-4a76-9916-fe3849e51b52",
   "metadata": {},
   "outputs": [],
   "source": [
    "bank_df = pd.read_csv(\"bank.csv\", sep=';')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "1e7e9325-10f8-4db7-b5fd-2abc963a8711",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',\n",
      "       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',\n",
      "       'previous', 'poutcome', 'y'],\n",
      "      dtype='object')\n"
     ]
    }
   ],
   "source": [
    "print(bank_df.columns)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "4f9c75dc-bfe9-44b9-a05f-ed6b1cbcefc6",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.preprocessing import LabelEncoder\n",
    "\n",
    "label_enc = LabelEncoder()\n",
    "bank_df['job'] = label_enc.fit_transform(bank_df['job'])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "2df72a15-3dab-46cc-8112-db7234199cf4",
   "metadata": {},
   "outputs": [],
   "source": [
    "bank_df = pd.read_csv(\"bank.csv\", sep=';')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "e025a0cf-5c47-40c3-9f88-8485afcf4275",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   age          job  marital  education default  balance housing loan  \\\n",
      "0   30   unemployed  married    primary      no     1787      no   no   \n",
      "1   33     services  married  secondary      no     4789     yes  yes   \n",
      "2   35   management   single   tertiary      no     1350     yes   no   \n",
      "3   30   management  married   tertiary      no     1476     yes  yes   \n",
      "4   59  blue-collar  married  secondary      no        0     yes   no   \n",
      "\n",
      "    contact  day month  duration  campaign  pdays  previous poutcome   y  \n",
      "0  cellular   19   oct        79         1     -1         0  unknown  no  \n",
      "1  cellular   11   may       220         1    339         4  failure  no  \n",
      "2  cellular   16   apr       185         1    330         1  failure  no  \n",
      "3   unknown    3   jun       199         4     -1         0  unknown  no  \n",
      "4   unknown    5   may       226         1     -1         0  unknown  no  \n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 4521 entries, 0 to 4520\n",
      "Data columns (total 17 columns):\n",
      " #   Column     Non-Null Count  Dtype \n",
      "---  ------     --------------  ----- \n",
      " 0   age        4521 non-null   int64 \n",
      " 1   job        4521 non-null   object\n",
      " 2   marital    4521 non-null   object\n",
      " 3   education  4521 non-null   object\n",
      " 4   default    4521 non-null   object\n",
      " 5   balance    4521 non-null   int64 \n",
      " 6   housing    4521 non-null   object\n",
      " 7   loan       4521 non-null   object\n",
      " 8   contact    4521 non-null   object\n",
      " 9   day        4521 non-null   int64 \n",
      " 10  month      4521 non-null   object\n",
      " 11  duration   4521 non-null   int64 \n",
      " 12  campaign   4521 non-null   int64 \n",
      " 13  pdays      4521 non-null   int64 \n",
      " 14  previous   4521 non-null   int64 \n",
      " 15  poutcome   4521 non-null   object\n",
      " 16  y          4521 non-null   object\n",
      "dtypes: int64(7), object(10)\n",
      "memory usage: 600.6+ KB\n",
      "None\n",
      "               age       balance          day     duration     campaign  \\\n",
      "count  4521.000000   4521.000000  4521.000000  4521.000000  4521.000000   \n",
      "mean     41.170095   1422.657819    15.915284   263.961292     2.793630   \n",
      "std      10.576211   3009.638142     8.247667   259.856633     3.109807   \n",
      "min      19.000000  -3313.000000     1.000000     4.000000     1.000000   \n",
      "25%      33.000000     69.000000     9.000000   104.000000     1.000000   \n",
      "50%      39.000000    444.000000    16.000000   185.000000     2.000000   \n",
      "75%      49.000000   1480.000000    21.000000   329.000000     3.000000   \n",
      "max      87.000000  71188.000000    31.000000  3025.000000    50.000000   \n",
      "\n",
      "             pdays     previous  \n",
      "count  4521.000000  4521.000000  \n",
      "mean     39.766645     0.542579  \n",
      "std     100.121124     1.693562  \n",
      "min      -1.000000     0.000000  \n",
      "25%      -1.000000     0.000000  \n",
      "50%      -1.000000     0.000000  \n",
      "75%      -1.000000     0.000000  \n",
      "max     871.000000    25.000000  \n"
     ]
    }
   ],
   "source": [
    "print(bank_df.head())\n",
    "print(bank_df.info())\n",
    "print(bank_df.describe())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "4ac82935-3fe1-4df5-aa8e-45f30595f119",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "age          0\n",
      "job          0\n",
      "marital      0\n",
      "education    0\n",
      "default      0\n",
      "balance      0\n",
      "housing      0\n",
      "loan         0\n",
      "contact      0\n",
      "day          0\n",
      "month        0\n",
      "duration     0\n",
      "campaign     0\n",
      "pdays        0\n",
      "previous     0\n",
      "poutcome     0\n",
      "y            0\n",
      "dtype: int64\n"
     ]
    }
   ],
   "source": [
    "print(bank_df.isnull().sum())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "41fb52a9-ff41-4f14-937e-869760d2c936",
   "metadata": {},
   "outputs": [],
   "source": [
    "label_enc = LabelEncoder()\n",
    "categorical_cols = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']\n",
    "\n",
    "for col in categorical_cols:\n",
    "    bank_df[col] = label_enc.fit_transform(bank_df[col])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "a2426b1b-1174-4682-990b-534999134b1c",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "from sklearn.preprocessing import StandardScaler\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "9cf0bde0-9f4d-45ca-bd0b-2c2cf2601ffc",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.preprocessing import StandardScaler  # <-- Add this if missing\n",
    "\n",
    "scaler = StandardScaler()\n",
    "num_cols = ['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']\n",
    "\n",
    "bank_df[num_cols] = scaler.fit_transform(bank_df[num_cols])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "e2af18cd-c993-491c-8f4c-e93784afbfc5",
   "metadata": {},
   "outputs": [],
   "source": [
    "X = bank_df.drop('y', axis=1)\n",
    "y = bank_df['y']\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "dcf30763-a3f8-40b9-a474-cc229b5c5e97",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "884db4bf-96bb-4ab4-ac8c-e426ee710a99",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split  # ✅ Fix import\n",
    "\n",
    "# Separate features (X) and target (y)\n",
    "X = bank_df.drop('y', axis=1)\n",
    "y = bank_df['y']\n",
    "\n",
    "# Train-test split\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "90ee1aad-3a4c-4da0-9c96-f1e10fbfdd4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.linear_model import LogisticRegression\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "def8341f-4ecd-465a-8841-8d96f19609be",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>#sk-container-id-1 {\n",
       "  /* Definition of color scheme common for light and dark mode */\n",
       "  --sklearn-color-text: #000;\n",
       "  --sklearn-color-text-muted: #666;\n",
       "  --sklearn-color-line: gray;\n",
       "  /* Definition of color scheme for unfitted estimators */\n",
       "  --sklearn-color-unfitted-level-0: #fff5e6;\n",
       "  --sklearn-color-unfitted-level-1: #f6e4d2;\n",
       "  --sklearn-color-unfitted-level-2: #ffe0b3;\n",
       "  --sklearn-color-unfitted-level-3: chocolate;\n",
       "  /* Definition of color scheme for fitted estimators */\n",
       "  --sklearn-color-fitted-level-0: #f0f8ff;\n",
       "  --sklearn-color-fitted-level-1: #d4ebff;\n",
       "  --sklearn-color-fitted-level-2: #b3dbfd;\n",
       "  --sklearn-color-fitted-level-3: cornflowerblue;\n",
       "\n",
       "  /* Specific color for light theme */\n",
       "  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n",
       "  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-icon: #696969;\n",
       "\n",
       "  @media (prefers-color-scheme: dark) {\n",
       "    /* Redefinition of color scheme for dark theme */\n",
       "    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n",
       "    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-icon: #878787;\n",
       "  }\n",
       "}\n",
       "\n",
       "#sk-container-id-1 {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 pre {\n",
       "  padding: 0;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-hidden--visually {\n",
       "  border: 0;\n",
       "  clip: rect(1px 1px 1px 1px);\n",
       "  clip: rect(1px, 1px, 1px, 1px);\n",
       "  height: 1px;\n",
       "  margin: -1px;\n",
       "  overflow: hidden;\n",
       "  padding: 0;\n",
       "  position: absolute;\n",
       "  width: 1px;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-dashed-wrapped {\n",
       "  border: 1px dashed var(--sklearn-color-line);\n",
       "  margin: 0 0.4em 0.5em 0.4em;\n",
       "  box-sizing: border-box;\n",
       "  padding-bottom: 0.4em;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-container {\n",
       "  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n",
       "     but bootstrap.min.css set `[hidden] { display: none !important; }`\n",
       "     so we also need the `!important` here to be able to override the\n",
       "     default hidden behavior on the sphinx rendered scikit-learn.org.\n",
       "     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n",
       "  display: inline-block !important;\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-text-repr-fallback {\n",
       "  display: none;\n",
       "}\n",
       "\n",
       "div.sk-parallel-item,\n",
       "div.sk-serial,\n",
       "div.sk-item {\n",
       "  /* draw centered vertical line to link estimators */\n",
       "  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n",
       "  background-size: 2px 100%;\n",
       "  background-repeat: no-repeat;\n",
       "  background-position: center center;\n",
       "}\n",
       "\n",
       "/* Parallel-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item::after {\n",
       "  content: \"\";\n",
       "  width: 100%;\n",
       "  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n",
       "  flex-grow: 1;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel {\n",
       "  display: flex;\n",
       "  align-items: stretch;\n",
       "  justify-content: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:first-child::after {\n",
       "  align-self: flex-end;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:last-child::after {\n",
       "  align-self: flex-start;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:only-child::after {\n",
       "  width: 0;\n",
       "}\n",
       "\n",
       "/* Serial-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-serial {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  align-items: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  padding-right: 1em;\n",
       "  padding-left: 1em;\n",
       "}\n",
       "\n",
       "\n",
       "/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\n",
       "clickable and can be expanded/collapsed.\n",
       "- Pipeline and ColumnTransformer use this feature and define the default style\n",
       "- Estimators will overwrite some part of the style using the `sk-estimator` class\n",
       "*/\n",
       "\n",
       "/* Pipeline and ColumnTransformer style (default) */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable {\n",
       "  /* Default theme specific background. It is overwritten whether we have a\n",
       "  specific estimator or a Pipeline/ColumnTransformer */\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "/* Toggleable label */\n",
       "#sk-container-id-1 label.sk-toggleable__label {\n",
       "  cursor: pointer;\n",
       "  display: flex;\n",
       "  width: 100%;\n",
       "  margin-bottom: 0;\n",
       "  padding: 0.5em;\n",
       "  box-sizing: border-box;\n",
       "  text-align: center;\n",
       "  align-items: start;\n",
       "  justify-content: space-between;\n",
       "  gap: 0.5em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label .caption {\n",
       "  font-size: 0.6rem;\n",
       "  font-weight: lighter;\n",
       "  color: var(--sklearn-color-text-muted);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:before {\n",
       "  /* Arrow on the left of the label */\n",
       "  content: \"▸\";\n",
       "  float: left;\n",
       "  margin-right: 0.25em;\n",
       "  color: var(--sklearn-color-icon);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "/* Toggleable content - dropdown */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content {\n",
       "  max-height: 0;\n",
       "  max-width: 0;\n",
       "  overflow: hidden;\n",
       "  text-align: left;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content pre {\n",
       "  margin: 0.2em;\n",
       "  border-radius: 0.25em;\n",
       "  color: var(--sklearn-color-text);\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted pre {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n",
       "  /* Expand drop-down */\n",
       "  max-height: 200px;\n",
       "  max-width: 100%;\n",
       "  overflow: auto;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n",
       "  content: \"▾\";\n",
       "}\n",
       "\n",
       "/* Pipeline/ColumnTransformer-specific style */\n",
       "\n",
       "#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator-specific style */\n",
       "\n",
       "/* Colorize estimator box */\n",
       "#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label label.sk-toggleable__label,\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  /* The background is the default theme color */\n",
       "  color: var(--sklearn-color-text-on-default-background);\n",
       "}\n",
       "\n",
       "/* On hover, darken the color of the background */\n",
       "#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "/* Label box, darken color on hover, fitted */\n",
       "#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator label */\n",
       "\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  font-family: monospace;\n",
       "  font-weight: bold;\n",
       "  display: inline-block;\n",
       "  line-height: 1.2em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label-container {\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "/* Estimator-specific */\n",
       "#sk-container-id-1 div.sk-estimator {\n",
       "  font-family: monospace;\n",
       "  border: 1px dotted var(--sklearn-color-border-box);\n",
       "  border-radius: 0.25em;\n",
       "  box-sizing: border-box;\n",
       "  margin-bottom: 0.5em;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "/* on hover */\n",
       "#sk-container-id-1 div.sk-estimator:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Specification for estimator info (e.g. \"i\" and \"?\") */\n",
       "\n",
       "/* Common style for \"i\" and \"?\" */\n",
       "\n",
       ".sk-estimator-doc-link,\n",
       "a:link.sk-estimator-doc-link,\n",
       "a:visited.sk-estimator-doc-link {\n",
       "  float: right;\n",
       "  font-size: smaller;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1em;\n",
       "  height: 1em;\n",
       "  width: 1em;\n",
       "  text-decoration: none !important;\n",
       "  margin-left: 0.5em;\n",
       "  text-align: center;\n",
       "  /* unfitted */\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted,\n",
       "a:link.sk-estimator-doc-link.fitted,\n",
       "a:visited.sk-estimator-doc-link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "div.sk-estimator:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "/* Span, style for the box shown on hovering the info icon */\n",
       ".sk-estimator-doc-link span {\n",
       "  display: none;\n",
       "  z-index: 9999;\n",
       "  position: relative;\n",
       "  font-weight: normal;\n",
       "  right: .2ex;\n",
       "  padding: .5ex;\n",
       "  margin: .5ex;\n",
       "  width: min-content;\n",
       "  min-width: 20ex;\n",
       "  max-width: 50ex;\n",
       "  color: var(--sklearn-color-text);\n",
       "  box-shadow: 2pt 2pt 4pt #999;\n",
       "  /* unfitted */\n",
       "  background: var(--sklearn-color-unfitted-level-0);\n",
       "  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted span {\n",
       "  /* fitted */\n",
       "  background: var(--sklearn-color-fitted-level-0);\n",
       "  border: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link:hover span {\n",
       "  display: block;\n",
       "}\n",
       "\n",
       "/* \"?\"-specific style due to the `<a>` HTML tag */\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link {\n",
       "  float: right;\n",
       "  font-size: 1rem;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1rem;\n",
       "  height: 1rem;\n",
       "  width: 1rem;\n",
       "  text-decoration: none;\n",
       "  /* unfitted */\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "#sk-container-id-1 a.estimator_doc_link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "</style><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>LogisticRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\" checked><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>LogisticRegression</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.6/modules/generated/sklearn.linear_model.LogisticRegression.html\">?<span>Documentation for LogisticRegression</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\"><pre>LogisticRegression()</pre></div> </div></div></div></div>"
      ],
      "text/plain": [
       "LogisticRegression()"
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sklearn.linear_model import LogisticRegression  # ✅ Import this\n",
    "\n",
    "# Train the model\n",
    "model = LogisticRegression()\n",
    "model.fit(X_train, y_train)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "2fc80fe9-a1ec-4a83-8fe9-52e9b4e0c4ed",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.metrics import accuracy_score, confusion_matrix, classification_report\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "dfd3e993-b9ae-47a1-ae6b-f8deb62c2e83",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Accuracy: 0.8939226519337017\n",
      "Confusion Matrix:\n",
      " [[791  16]\n",
      " [ 80  18]]\n",
      "Classification Report:\n",
      "               precision    recall  f1-score   support\n",
      "\n",
      "           0       0.91      0.98      0.94       807\n",
      "           1       0.53      0.18      0.27        98\n",
      "\n",
      "    accuracy                           0.89       905\n",
      "   macro avg       0.72      0.58      0.61       905\n",
      "weighted avg       0.87      0.89      0.87       905\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import accuracy_score, confusion_matrix, classification_report  \n",
    "\n",
    "# Predict the test set\n",
    "y_pred = model.predict(X_test)\n",
    "\n",
    "# Evaluation\n",
    "print(\"Accuracy:\", accuracy_score(y_test, y_pred))\n",
    "print(\"Confusion Matrix:\\n\", confusion_matrix(y_test, y_pred))\n",
    "print(\"Classification Report:\\n\", classification_report(y_test, y_pred))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "97fede8b-0446-497b-9e1f-334fc316c28f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAgcAAAGzCAYAAAC7ErTFAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjEsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvc2/+5QAAAAlwSFlzAAAPYQAAD2EBqD+naQAAMZhJREFUeJzt3Q2cTXX+wPHvDGMwY0aDmWFr0Fae8pCHmDyUTCahPPW0YkiURWWQphWRaKkltahdYbdsxUYhMUYopjAteY5YhJkhGQ81ZsY5/9fv1/9e9xyj7th73Vvn8+51uvec87vn/u5I53u/39/vNyGmaZoCAADw/0JdTwAAABSCAwAAYEFwAAAALAgOAACABcEBAACwIDgAAAAWBAcAAMCC4AAAAFgQHAAAAAuCA8DDnj17pH379hIdHS0hISGyaNEin17/v//9r77unDlzfHrdX7PbbrtNbwCCB8EBgs4333wjjz76qFx77bVStmxZiYqKkpYtW8orr7wiP/74o1/fOyUlRbZu3SovvPCC/POf/5SmTZvKb0WfPn10YKJ+nsX9HFVgpM6r7aWXXirx9Y8cOSLPPfecbN682Uc9BhAopQP2zkAxli5dKvfee6+Eh4dL79695cYbb5SCggL57LPPZMSIEbJ9+3Z54403/PLe6oaZmZkpf/rTn2Tw4MF+eY/q1avr9wkLC5NAKF26tPzwww+yePFiue+++yzn3n77bR2M5efnX9a1VXAwduxYqVGjhjRq1Mjr161YseKy3g+A/xAcIGjs379fHnjgAX0DXbVqlVStWtV9btCgQbJ3714dPPjLsWPH9GPFihX99h7qW7m6AQeKCrpUFuZf//rXRcHBvHnzpGPHjvLvf//7ivRFBSnly5eXMmXKXJH3A+A9ygoIGpMmTZIzZ87IrFmzLIGBy3XXXSdPPPGEe7+oqEief/55+f3vf69veuob6zPPPCPnzp2zvE4d79Spk84+3HzzzfrmrEoW//jHP9xtVDpcBSWKylCom7h6nSsd73ruSb1GtfOUnp4urVq10gFGZGSk1KpVS/fpl8YcqGCodevWEhERoV97zz33yM6dO4t9PxUkqT6pdmpsRN++ffWN1lt/+MMfZNmyZXLy5En3sY0bN+qygjpnd+LECRk+fLjUr19ffyZVlujQoYNs2bLF3Wb16tXSrFkz/Vz1x1WecH1ONaZAZYGysrKkTZs2Oihw/VzsYw5UaUf9Gdk/f3Jyslx11VU6QwHAvwgOEDRUqlvdtG+55Rav2j/yyCMyevRoady4sUyZMkVuvfVWmThxos4+2Kkbao8ePeSOO+6Ql19+Wd9k1A1WlSmUbt266WsoDz74oB5vMHXq1BL1X11LBSEqOBk3bpx+n7vvvlvWrVv3s69buXKlvvHl5ubqACA1NVXWr1+vv+GrYMJOfeM/ffq0/qzquboBq3S+t9RnVTfu999/35I1qF27tv5Z2u3bt08PzFSf7S9/+YsOntS4DPXzdt2o69Spoz+zMmDAAP3zU5sKBFy+++47HVSokoP62bZt27bY/qmxJVWqVNFBwvnz5/Wx119/XZcfXn31ValWrZrXnxXAZTKBIJCXl2eq/xzvuecer9pv3rxZt3/kkUcsx4cPH66Pr1q1yn2sevXq+tjatWvdx3Jzc83w8HBz2LBh7mP79+/X7SZPnmy5ZkpKir6G3ZgxY3R7lylTpuj9Y8eOXbLfrveYPXu2+1ijRo3M2NhY87vvvnMf27JlixkaGmr27t37ovd7+OGHLdfs2rWrWalSpUu+p+fniIiI0M979OhhtmvXTj8/f/68GR8fb44dO7bYn0F+fr5uY/8c6uc3btw497GNGzde9Nlcbr31Vn1u5syZxZ5Tm6fly5fr9uPHjzf37dtnRkZGml26dPnFzwjAN8gcICicOnVKP1aoUMGr9h999JF+VN+yPQ0bNkw/2scm1K1bV6ftXdQ3U5XyV9+KfcU1VuGDDz4QwzC8es3Ro0f16H6VxYiJiXEfb9Cggc5yuD6np8cee8yyrz6X+lbu+hl6Q5UPVCkgOztblzTUY3ElBUWVbEJDf/pfhfomr97LVTL58ssvvX5PdR1VcvCGmk6qZqyobITKdKgyg8oeALgyCA4QFFQdW1Hpcm8cOHBA37DUOARP8fHx+iatzntKSEi46BqqtPD999+Lr9x///26FKDKHXFxcbq88d577/1soODqp7rR2qlU/fHjx+Xs2bM/+1nU51BK8lnuuusuHYi9++67epaCGi9g/1m6qP6rksv111+vb/CVK1fWwdVXX30leXl5Xr/n7373uxINPlTTKVXApIKnadOmSWxsrNevBfC/IThA0AQHqpa8bdu2Er3OPiDwUkqVKlXscdM0L/s9XPVwl3LlysnatWv1GIJevXrpm6cKGFQGwN72f/G/fBYXdZNX38jnzp0rCxcuvGTWQJkwYYLO0KjxA2+99ZYsX75cD7ysV6+e1xkS18+nJP7zn//ocRiKGuMA4MohOEDQUAPe1AJIaq2BX6JmFqgbkxph7yknJ0ePwnfNPPAF9c3cc2S/iz07oahsRrt27fTAvR07dujFlFTa/pNPPrnk51B279590bldu3bpb+lqBoM/qIBA3YBVtqa4QZwuCxYs0IMH1SwS1U6l/JOSki76mXgbqHlDZUtUCUKVg9QARzWTRc2oAHBlEBwgaDz11FP6RqjS8uomb6cCBzWS3ZUWV+wzCtRNWVHz9X1FTZVU6XOVCfAcK6C+cdun/Nm5FgOyT690UVM2VRv1Dd7zZqsyKGp0vutz+oO64aupoK+99poux/xcpsKelZg/f74cPnzYcswVxBQXSJXUyJEj5eDBg/rnov5M1VRSNXvhUj9HAL7FIkgIGuomrKbUqVS8qrd7rpCopvapG5IauKc0bNhQ3yzUaonqZqSm1W3YsEHfTLp06XLJaXKXQ31bVjerrl27yuOPP67XFJgxY4bccMMNlgF5avCcKiuowERlBFRKfPr06XL11VfrtQ8uZfLkyXqKX2JiovTr10+voKim7Kk1DNTURn9RWY5Ro0Z5ldFRn019k1fTTFWKX41TUNNO7X9+arzHzJkz9XgGFSw0b95catasWaJ+qUyL+rmNGTPGPbVy9uzZei2EZ599VmcRAPiZj2Y9AD7z9ddfm/379zdr1KhhlilTxqxQoYLZsmVL89VXX9XT6lwKCwv19LuaNWuaYWFh5jXXXGOmpaVZ2ihqGmLHjh1/cQrdpaYyKitWrDBvvPFG3Z9atWqZb7311kVTGTMyMvRUzGrVqul26vHBBx/Un8f+HvbpfitXrtSfsVy5cmZUVJTZuXNnc8eOHZY2rvezT5VU11LH1bW9ncp4KZeayqimfFatWlX3T/UzMzOz2CmIH3zwgVm3bl2zdOnSls+p2tWrV6/Y9/S8zqlTp/SfV+PGjfWfr6ehQ4fq6Z3qvQH4V4j6l78DEAAA8OvBmAMAAGBBcAAAACwIDgAAgAXBAQAAsCA4AAAAFgQHAADAguAAAAAE5wqJhcd996tzgd+KctUu/JppABcUFViX7w7me1JYZetqor8GQRMcAAAQNAzf/SbVXyPKCgAAwILMAQAAdqYhTkZwAACAnUFwAAAAPJgOzxww5gAAAFiQOQAAwM5wduaA4AAAADvT2cEBZQUAAGBB5gAAADvD2YsgERwAAGBnUlYAAABwI3MAAICd4ezMAcEBAAA2JmUFAACAC8gcAABgZzg7c0BwAACAnUlwAAAAPBnOXueAMQcAAMCCzAEAAHYmZQUAAODJcHZwQFkBAABYkDkAAMDOdHbmgOAAAAA7w9nBAWUFAABgQeYAAAAb03T2OgcEBwAA2JmUFQAAANzIHAAAYGc4O3NAcAAAgJ1JcAAAADwZzh6QyJgDAABgQeYAAAA7k7ICAADwZDg7OKCsAAAALMgcAABgZzo7c0BwAACAneHs4ICyAgAAsCA4AACguMyB4aOtBGrUqCEhISEXbYMGDdLn8/Pz9fNKlSpJZGSkdO/eXXJycizXOHjwoHTs2FHKly8vsbGxMmLECCkqKipRPygrAAAQJL+VcePGjXL+/IX33rZtm9xxxx1y77336v2hQ4fK0qVLZf78+RIdHS2DBw+Wbt26ybp16/R59VoVGMTHx8v69evl6NGj0rt3bwkLC5MJEyZ43Y8Q0zRNCQKFx/cFugtA0ClXrXWguwAEpaKCw369/o9r5/jsWuXa9Lns1z755JOyZMkS2bNnj5w6dUqqVKki8+bNkx49eujzu3btkjp16khmZqa0aNFCli1bJp06dZIjR45IXFycbjNz5kwZOXKkHDt2TMqUKePV+1JWAADAj2WFc+fO6Ru756aO/ZKCggJ566235OGHH9alhaysLCksLJSkpCR3m9q1a0tCQoIODhT1WL9+fXdgoCQnJ+v33L59u9cfn+AAAIDipjKavtkmTpyoSwCemzr2SxYtWiQnT56UPn1+yjxkZ2frb/4VK1a0tFOBgDrnauMZGLjOu855izEHAAD4cSpjWlqapKamWo6Fh4f/4utmzZolHTp0kGrVqsmVRnAAAIAfhYeHexUMeDpw4ICsXLlS3n//ffcxNchQlRpUNsEze6BmK6hzrjYbNmywXMs1m8HVxhuUFQAA8GNZ4XLMnj1bT0NUMw9cmjRpomcdZGRkuI/t3r1bT11MTEzU++px69atkpub626Tnp4uUVFRUrduXa/fn8wBAABBtEKiYRg6OEhJSZHSpS/cptVYhX79+ukSRUxMjL7hDxkyRAcEaqaC0r59ex0E9OrVSyZNmqTHGYwaNUqvjVCS7AXBAQAAQWTlypU6G6BmKdhNmTJFQkND9eJHasaDmokwffp09/lSpUrpqY8DBw7UQUNERIQOMsaNG1eiPrDOARDEWOcACNA6B8tf89m1yiUPll8bMgcAANgZ/OIlAAAANzIHAADYGc7OHBAcAABgZzo7OKCsAAAALMgcAABgZzg7c0BwAACAnUlwAAAAPBnODg4YcwAAACzIHAAAYGc6O3NAcAAAgJ3h7OCAsgIAALAgcwAAgJ3h7MwBwQEAAHZmUPzC4oChrAAAACzIHAAAYGdQVgAAAJ4MZwcHlBUAAIAFmQMAAOxMZ2cOCA4AALAzCA4AAIAnk6mMAAAAbmQOAACwMygrAAAAT4azgwPKCgAAwILMAQAAdqazMwcEBwAA2JgGsxUAAADcyBwAAGBnUFYAAACeTGcHB5QVAACABZkDAADsDGcPSCQ4AADAznB2WYHgAAAAO8PZwQFjDgAAgAWZAwAA7EzGHAAAAE8GZQX8xrXvniI3tuxw0Tb+5b/q8we/PSKPp42T1h3vl+Z3dJNhz06Q4ye+t1zj9bn/kp6PpkrT27tIYnKPAH0SwL9at2ouixbOkYP/zZKigsNy993JF7WpXfs6Wfj+bPnu2E7J+36PZK5fKtdcUy0g/cVv0+HDh+Whhx6SSpUqSbly5aR+/fqyadMm93nTNGX06NFStWpVfT4pKUn27NljucaJEyekZ8+eEhUVJRUrVpR+/frJmTNnvO4DwYEDvPP3V2T1h2+7t79NnaCPt2/bWn74MV8GDP2ThEiIzJr2ovxz5stSWFgkg596TgyPyFkdS27bWu7v2jGAnwTwr4iI8vLVVztkyBN/Kvb8tddWlzWfLJLdu/dKuzt6yE1NkuSFCVMlP//cFe8rrsBURsNHWwl8//330rJlSwkLC5Nly5bJjh075OWXX5arrrrK3WbSpEkybdo0mTlzpnzxxRcSEREhycnJkp+f726jAoPt27dLenq6LFmyRNauXSsDBgzwuh8hpgpBgkDh8X2B7oJjvDh1pqxZv0E+eneWrN/wpQwcPlrWf/yeREZE6POnz5yVW+68V96Y8oIkNrvJ8tpFS9Plz9Nel8zlCwLUe2cpV611oLvgWCpz0K3Hw/Lhh8vdx95+a7oOlPv0fTygfcNPfz7+9MPkh312rfIj3vS67dNPPy3r1q2TTz/9tNjz6pZdrVo1GTZsmAwfPlwfy8vLk7i4OJkzZ4488MADsnPnTqlbt65s3LhRmjZtqtt8/PHHctddd8m3336rX+/zzMHx48d11NK1a1dJTEzUm3o+efJkOXbsWEkvhyussLBQlqz4RLp2bC8hISF6PyREpExYmLtNeJkwCQ0NkS+/2h7QvgLBRP19uatDO9mzZ598tORtOfLtFln/2eJiSw+Ap3PnzsmpU6csmzpWnA8//FDf0O+9916JjY2Vm266Sf72t7+5z+/fv1+ys7N1KcElOjpamjdvLpmZmXpfPapSgiswUFT70NBQnWnwRomCAxWF3HDDDTqdoTrTpk0bvann6ljt2rUtdRFf/KDgWxlrM+X0mTPS5a479H6DerWlXNmy8pfpb8qP+fm6zPDSa3+X8+cNOf7diUB3FwgasbGVpUKFSHlqxCBZvmK1dOj4B1n0wcey4L2/S5vWLQLdPQRxWWHixIn6Pum5qWPF2bdvn8yYMUOuv/56Wb58uQwcOFAef/xxmTt3rj6vAgNFZQo8qX3XOfWoAgtPpUuXlpiYGHcbn85WGDJkiI5mVJ1DRdH2VMdjjz2m27iil0tRP5SxY8dajo0a8biMfuqJknQHl+H9JculVYumElulkt6PuaqivPz8M/L8S6/J2ws+1BmDDkm3Sd1a1130Zww4mfrWpXy4eLm8Mu2nb3JbtmyXxMSmMmBAL1n76ecB7iF8yfThbIW0tDRJTU21HAsPDy+2rRrrpb7xT5jw09gwlTnYtm2bvu+mpKTIlVKi4GDLli26plHcTUMdGzp0qP4gl/ODCj3t3/oRRI5k58jnmzbL1AmjLMdbNm8iH8+fLd+fzJNSpUpJVIVIubXzH+TOdlUD1lcg2Bw/fkKX4XbutI4K37Vrj7S85eaA9QvBLzw8/JLBgJ2agaDGC3iqU6eO/Pvf/9bP4+Pj9WNOTo5u66L2GzVq5G6Tm5truUZRUZGeweB6vU/LCuqiGzZsuOR5dc6e6iiO+iGp6RWem7c/OFy+hUvTJeaqaGmTWPz/yK6qGK0Dgy+yNsuJ709K21akSgEXFRhs2rRFbrjh95bj119/rRw4+G3A+oXf1myFli1byu7duy3Hvv76a6levbp+XrNmTX0vzsjIcJ9XpXk1lkCNAVTU48mTJyUrK8vdZtWqVTorocYm+DxzoEZGqqkQ6g3btWvnDgRUxKI6qgZNvPTSSyW5JK4Q9R+FmmlwT4ckKV26lOXcwqUr5Nrq1+jgYMv2XXo2Q+/7u0rN6le72xzNzpW8U6flaE6uHo+w6+tv9PGEq6tJ+fLlrvjnAfw1lfG662q692vWSJCGDevJiRPfy6FDR+Slv8yQf709Qz799HNZvWa9JLe/TTp1vEPaJbH2x2+OGZhFkFQG/pZbbtFlhfvuu09/6X7jjTf05srSP/nkkzJ+/Hg9LkEFC88++6yegdClSxd3puHOO++U/v3763KECmwHDx6sZzJ4M1PhsqYyvvvuuzJlyhQdIJw/f14fU6noJk2a6FKB+jCXg6mM/rXuiyx5NHWULPnX36RGwoWbvjJlxpuy6KOV+ub/u6pxcl+Xu3Rw4Fk++tP4l+WDZSsvuu6br/5Zbm7c4Ip8BidiKuOVdWubRMlYefE03bn/eE/6PTJUP++Tcr+MfGqIXH11vOz+ep+MHfeSLF68IgC9dTZ/T2U8O66nz64VMfrtErVX6xKo8rta2Ejd/NW9Vd3oXdRte8yYMTpgUBmCVq1ayfTp0/WEARdVQlABweLFi/V4me7du+uJA5GRkf5d50BFImpao1K5cmW9YMP/guAAuBjBAeC84OBX/bsVVDDgORgCAIDfDMPZv1uBX7wEAICdERSLBwcMv1sBAABYkDkAACBIZisEC4IDAADsDMoKAAAAbmQOAADw4+9W+DUiOAAAwM6grAAAAOBG5gAAADvD2ZkDggMAAOxMxhwAAABPhrMzB4w5AAAAFmQOAACwMR2eOSA4AADAznB2cEBZAQAAWJA5AADAzmC2AgAA8GRQVgAAAHAjcwAAgJ3h7MwBwQEAADam6ezggLICAACwIHMAAICd4ezMAcEBAAB2BsEBAADwYDo8OGDMAQAAsCBzAACAneHszAHBAQAAdoY4GmUFAABgQeYAAAAbk7ICAACwMJwdHFBWAAAAFmQOAACwM8TRCA4AALAxKSsAAABcQOYAAAA7QxyN4AAAABuTsgIAALgoc2D4aCuB5557TkJCQixb7dq13efz8/Nl0KBBUqlSJYmMjJTu3btLTk6O5RoHDx6Ujh07Svny5SU2NlZGjBghRUVFJeoHmQMAAIJIvXr1ZOXKle790qUv3KqHDh0qS5culfnz50t0dLQMHjxYunXrJuvWrdPnz58/rwOD+Ph4Wb9+vRw9elR69+4tYWFhMmHCBK/7QHAAAICN6cMxB+fOndObp/DwcL0VRwUD6uZul5eXJ7NmzZJ58+bJ7bffro/Nnj1b6tSpI59//rm0aNFCVqxYITt27NDBRVxcnDRq1Eief/55GTlypM5KlClTxqs+U1YAAMCPZYWJEyfqb/memzp2KXv27JFq1arJtddeKz179tRlAiUrK0sKCwslKSnJ3VaVHBISEiQzM1Pvq8f69evrwMAlOTlZTp06Jdu3b/f645M5AADAj9LS0iQ1NdVy7FJZg+bNm8ucOXOkVq1auiQwduxYad26tWzbtk2ys7P1N/+KFStaXqMCAXVOUY+egYHrvOuctwgOAADwY1kh/GdKCHYdOnRwP2/QoIEOFqpXry7vvfeelCtXTq4UygoAAATJbAU7lSW44YYbZO/evXocQkFBgZw8edLSRs1WcI1RUI/22Quu/eLGMVwKwQEAAEHqzJkz8s0330jVqlWlSZMmetZBRkaG+/zu3bv1mITExES9rx63bt0qubm57jbp6ekSFRUldevW9fp9KSsAAODHskJJDB8+XDp37qxLCUeOHJExY8ZIqVKl5MEHH9QDGfv166fHL8TExOgb/pAhQ3RAoGYqKO3bt9dBQK9evWTSpEl6nMGoUaP02gjeljYUggMAAIIkOPj22291IPDdd99JlSpVpFWrVnqaonquTJkyRUJDQ/XiR2p6pJqJMH36dPfrVSCxZMkSGThwoA4aIiIiJCUlRcaNG1eifoSYphkUa0QWHt8X6C4AQadctdaB7gIQlIoKDvv1+jltb/XZteI+WSO/Now5AAAAFpQVAACwM0PEyQgOAAAIkjEHwYKyAgAAsCBzAACAjWlQVgAAAB5MygoAAAAXkDkAAMDGZLYCAADwZFJWAAAAuIDMAQAANiazFQAAgCczKH7rUOAQHAAAYGM6PHPAmAMAAGBB5gAAABvT4ZkDggMAAGxMh485oKwAAAAsyBwAAGBjUlYAAACeTIcvn0xZAQAAWJA5AADAxnT471YgOAAAwMagrAAAAHABmQMAAGxMh2cOCA4AALAxmcoIAAA8mayQCAAAcAGZAwAAbEzKCgAAwJPh8AGJlBUAAIAFmQMAAGxMh2cOCA4AALAxma0AAABwAZkDAABsDMoKAADAk+nw4ICyAgAAsCA4AACgmAGJpo+2y/Xiiy9KSEiIPPnkk+5j+fn5MmjQIKlUqZJERkZK9+7dJScnx/K6gwcPSseOHaV8+fISGxsrI0aMkKKiohK9N8EBAADFjDkwfLRdjo0bN8rrr78uDRo0sBwfOnSoLF68WObPny9r1qyRI0eOSLdu3dznz58/rwODgoICWb9+vcydO1fmzJkjo0ePLtH7h5hmcEzYqFmpYaC7AASdQ6ePB7oLQFAqKjjs1+tv/F1Xn12r2eGFJWp/5swZady4sUyfPl3Gjx8vjRo1kqlTp0peXp5UqVJF5s2bJz169NBtd+3aJXXq1JHMzExp0aKFLFu2TDp16qSDhri4ON1m5syZMnLkSDl27JiUKVPGqz6QOQAAwI/OnTsnp06dsmzq2KWosoH69p+UlGQ5npWVJYWFhZbjtWvXloSEBB0cKOqxfv367sBASU5O1u+5fft2r/tMcAAAgB/LChMnTpTo6GjLpo4V55133pEvv/yy2PPZ2dn6m3/FihUtx1UgoM652ngGBq7zrnPeYiojAAA2pg+vlZaWJqmpqZZj4eHhF7U7dOiQPPHEE5Keni5ly5aVQCJzAACAH4WHh0tUVJRlKy44UGWD3NxcPd6gdOnSelODDqdNm6afqwyAGmh48uRJy+vUbIX4+Hj9XD3aZy+49l1tvEFwAABAEMxWaNeunWzdulU2b97s3po2bSo9e/Z0Pw8LC5OMjAz3a3bv3q2nLiYmJup99aiuoYIMF5WJUAFJ3bp1ve4LZQUAAIJghcQKFSrIjTfeaDkWERGh1zRwHe/Xr58uUcTExOgb/pAhQ3RAoGYqKO3bt9dBQK9evWTSpEl6nMGoUaP0IMfishWXQnAAAMCvxJQpUyQ0NFQvfqRmPKiZCGrKo0upUqVkyZIlMnDgQB00qOAiJSVFxo0bV6L3YZ0DIIixzgEQmHUOPo3/aR0BX2idvUB+bcgcAABgYwq/eAkAAMCNzAEAADZGUBTcA4fgAAAAG8PhZQWCAwAAbEyHBweMOQAAABZkDgAAsDHE2QgOAACwMSkrAAAAXEDmAAAAG0OcjeAAAAAbQ5yNsgIAALAgcwAAgI3p8AGJBAcAANgYzo4NKCsAAAArMgcAANgYlBUAAIAnU5yN4AAAABtDnI0xBwAAwILMAQAANkYIYw4AAIAHU5yNsgIAALAgcwAAgI0hzkZwAACAjeHsIQeUFQAAgBWZAwAAbAxWSAQAAJ5McTbKCgAAwILMAQAANoazqwoEBwAA2BnibAQHAADYmOJsjDkAAAAWZA4AALAxGHMAAAA8GeJslBUAAIAFmQMAAGwMcTaCAwAAbEyHjzmgrAAAQJCYMWOGNGjQQKKiovSWmJgoy5Ytc5/Pz8+XQYMGSaVKlSQyMlK6d+8uOTk5lmscPHhQOnbsKOXLl5fY2FgZMWKEFBUVlagfBAcAABRTVjB8tJXE1VdfLS+++KJkZWXJpk2b5Pbbb5d77rlHtm/frs8PHTpUFi9eLPPnz5c1a9bIkSNHpFu3bu7Xnz9/XgcGBQUFsn79epk7d67MmTNHRo8eXaJ+hJimGRRrPdSs1DDQXQCCzqHTxwPdBSAoFRUc9uv1X7vmIZ9da/Cht/6n18fExMjkyZOlR48eUqVKFZk3b55+ruzatUvq1KkjmZmZ0qJFC51l6NSpkw4a4uLidJuZM2fKyJEj5dixY1KmTBmv3pPMAQAAfnTu3Dk5deqUZVPHfonKArzzzjty9uxZXV5Q2YTCwkJJSkpyt6ldu7YkJCTo4EBRj/Xr13cHBkpycrJ+T1f2wRsEBwAA2Jg+3CZOnCjR0dGWTR27lK1bt+rxBOHh4fLYY4/JwoULpW7dupKdna2/+VesWNHSXgUC6pyiHj0DA9d51zlvMVsBAAA/rpCYlpYmqamplmPqxn8ptWrVks2bN0teXp4sWLBAUlJS9PiCK4ngAAAAP65zEB4e/rPBgJ3KDlx33XX6eZMmTWTjxo3yyiuvyP33368HGp48edKSPVCzFeLj4/Vz9bhhwwbL9VyzGVxtvEFZAQCAIGYYhh6joAKFsLAwycjIcJ/bvXu3nrqoxiQo6lGVJXJzc91t0tPT9bRIVZrwFpkDAACCZIXEtLQ06dChgx5kePr0aT0zYfXq1bJ8+XI9VqFfv366RKFmMKgb/pAhQ3RAoGYqKO3bt9dBQK9evWTSpEl6nMGoUaP02gglyV4QHAAAYGMG6H3VN/7evXvL0aNHdTCgFkRSgcEdd9yhz0+ZMkVCQ0P14kcqm6BmIkyfPt39+lKlSsmSJUtk4MCBOmiIiIjQYxbGjRtXon6wzgEQxFjnAAjMOgcvJfhunYPhB/+3dQ4CgcwBAAB+nK3wa0RwAACAjSHOxmwFAABgQeYAAAAbU5yN4AAAABvD4eEBZQUAAGBB5gAAABtDnI3gAAAAG1OcjeAAAAAbQ5yNMQcAAMCCzAEAADYGKyQCAABPhsNHHVBWAAAAFmQOAACwMcXZCA4AALAxxNkoKwAAAAsyBwAA2BgOLywQHAAAYGOKs1FWAAAAFmQOAACwMcTZCA4AALAxHF5YIDgAAMDGFGdjzAEAALAgcwAAgI0hzkZwAACAjenwwgJlBQAAYEHmAAAAG0OcjeAAAAAbg7ICAADABWQOAACwMcXZCA4AALAxHB4eUFZwoNDQUElNGyRrv/xIdn77hazetESGDBtwUbuhT/9Rvti+Urf55/uvS41rEwLSX+BKad2quSxaOEcO/jdLigoOy913J1vOR0SUl1emjpf/7tskp/P2yldbPpEB/XsFrL+AvxAcONBjT/SVnn3vlTEjJ0pSYlf589ipMuDxPtJnwB/cbR59vK/0GfCgjBo+Xrq2f0h+/OFHmTt/hpQJLxPQvgP+pG7+X321Q4Y88adiz780eYwkt79NUvoMkRsb3CbTpv1dpr0yXjp1uuOK9xX+n61g+Gj7NaKs4ECNmzWS9GWr5ZP0T/X+4UNHpHP3DtKw8Y3uNg8/2lNee/lvup0ybOAo2bhrlbS/63ZZsvDjgPUd8KePl3+it0tJTGwq/3xrgaxZm6n3/z7rbenf/yG5udlNsmRJ+hXsKfzNpKwAp/ly42Zp2eZmqfn76nq/Tr0bpFnzm2T1ys/0/jXVfyex8VXkszVfuF9z+vQZ2Zy1VRo3axCwfgOBlpm5SWcJqlWL1/u33XqL3HD9tZKevibQXYOPGWQOfOvQoUMyZswYefPNNy/Z5ty5c3rzZJqGhIQQq1wJM6a+KZEVImXl54vk/PnzUqpUKXnphVflgwUf6fNVYivrx+PHvrO8Tu27zgFO9MSTz8rMGZP0mITCwkIxDEMeHfiUfPrZhUAa+C3w+d34xIkTMnfu3J9tM3HiRImOjrZsJ3/M9XVXcAkduyTLPT3ukicGpEnntg/I8EHPSv9BKdLtgc6B7hoQ1AYP6ivNmzeWLl37yM0tOsiIp8bJq6+8IO1ubx3orsEPZQXTR/84InPw4Ycf/uz5ffv2/eI10tLSJDU11XKsQY2WJe0KLlPa2KEy85U33WMHdu/cK7+7pqr88cl+8v47i+VY7nF9vHKVSnIs56fnrv0d23YHrN9AIJUtW1bGP/+09Lj3EfloWYY+tnXrTmnYsJ6kDn1UMlb9NIYHvw1GgN5XfXl+//33ZdeuXVKuXDm55ZZb5M9//rPUqlXL3SY/P1+GDRsm77zzjs7CJycny/Tp0yUuLs7d5uDBgzJw4ED55JNPJDIyUlJSUvS1S5cu7Z/goEuXLhISEiKmeeloSJ3/OeHh4XqzvoaSwpVSrlxZnQ71pMoLof//Z3DowGHJzT4mLds0l53/HwxEVoiQRk3qy1uz5wekz0CghYWVljJlyhTzd8fQ04MBX1izZo0MGjRImjVrJkVFRfLMM89I+/btZceOHRIREaHbDB06VJYuXSrz58/XmffBgwdLt27dZN26de7/n3fs2FHi4+Nl/fr1cvToUendu7eEhYXJhAkT/BMcVK1aVUco99xzT7HnN2/eLE2aNCnpZXEFZSxfI4NS+8uRb7Pl613fSL0GtaXfwF4yf94H7jZvvv62DB7WX/6774AOFlKfGSQ52cdkxUerAtp3wN9TGa+7rqZ7v2aNBJ0ZOHHiezl06IisWbNeXnxxlPz4Y74cOPittGmdKL0e6i7DR4wLaL/he8bPfAH2p48/ts4GmzNnjsTGxkpWVpa0adNG8vLyZNasWTJv3jy5/fbbdZvZs2dLnTp15PPPP5cWLVrIihUrdDCxcuVKnU1o1KiRPP/88zJy5Eh57rnndJDr8+BA3fhVJy8VHPxSVgGB99zTL+pFkJ6f/IxUqhyjb/r/mrtApk1+3d3m9WmzpXz5cjLhL6MlKrqCbPziP9Lnvj9KwbmCgPYd8KemTRpKxsoF7v2XX3pOP879x3vS75Gh8oeH/igvjE+Tf8x9VWJiKsqBg4fl2dGT5PU3/hHAXsMfTB9eq7hB+MVl0IujggElJiZGP6r7rxoMm5SU5G5Tu3ZtSUhIkMzMTB0cqMf69etbygyq9KDKDNu3b5ebbrrpF983xCzhnfzTTz+Vs2fPyp133lnseXVu06ZNcuutt5bkslKzUsMStQec4NDpC2M+AFygVrD0p4eqd/PZta7r20DGjh1rOaZm9alv8T9HlbDuvvtuOXnypHz22U9TzVXGoG/fvhcFGzfffLO0bdtWj08YMGCAHDhwQJYvX+4+/8MPP+iyxEcffSQdOnTwfeagdeufH5Wr3rykgQEAAL/V362QVswgfG+yBmrswbZt29yBwZXECokAANiYPgwOvC0heFKDDJcsWSJr166Vq6++2n1cDTIsKCjQ2YSKFSu6j+fk5OhzrjYbNmywXE+dd53zBkNsAQAIEqZp6sBg4cKFsmrVKqlZ88IAWde4PzXrICPjp+m0yu7du/XUxcTERL2vHrdu3Sq5uRfWD0pPT5eoqCipW7euV/0gcwAAQJCsczBo0CA9ruCDDz6QChUqSHZ2tj6upiyqdQ/UY79+/XSZQg1SVDf8IUOG6IBADUZU1NRHFQT06tVLJk2apK8xatQofW1vMxgEBwAA+HHMQUnMmDFDP952222W42q6Yp8+ffTzKVOm6LU1unfvblkEyUUtia9KEmp2ggoa1FhAtQjSuHHeT7kt8WwFf2G2AnAxZisAgZmt0KP63T671oIDP7+ycDBizAEAALCgrAAAgI0hzkZwAACAjRkcFfeAoawAAAAsyBwAABAksxWCBcEBAAA2hjgbZQUAAGBB5gAAAD/+boVfI4IDAABsDIcHB5QVAACABZkDAABsTIevc0BwAACAjSHORnAAAICNyZgDAACAC8gcAABgYzg8c0BwAACAjenwAYmUFQAAgAWZAwAAbAzKCgAAwJPp8OCAsgIAALAgcwAAgI3h8AGJBAcAANiY4myUFQAAgAWZAwAAbAyH5w4IDgAAsDEIDgAAgCfT4QMSGXMAAAAsyBwAAGBjUFYAAACeTIcHB5QVAACABZkDAABsTIcPSCQ4AADAxqCsAAAAcAGZAwAAbEzKCgAAwJNBWQEAAOACggMAAIpZ58D00T8lsXbtWuncubNUq1ZNQkJCZNGiRdZ+maaMHj1aqlatKuXKlZOkpCTZs2ePpc2JEyekZ8+eEhUVJRUrVpR+/frJmTNnStQPggMAAGwM0/TZVhJnz56Vhg0byl//+tdiz0+aNEmmTZsmM2fOlC+++EIiIiIkOTlZ8vPz3W1UYLB9+3ZJT0+XJUuW6IBjwIABJepHiBkkoy5qVmoY6C4AQefQ6eOB7gIQlIoKDvv1+vXimvvsWttzvris16nMwcKFC6VLly56X92uVUZh2LBhMnz4cH0sLy9P4uLiZM6cOfLAAw/Izp07pW7durJx40Zp2rSpbvPxxx/LXXfdJd9++61+vTfIHAAA4Efnzp2TU6dOWTZ1rKT2798v2dnZupTgEh0dLc2bN5fMzEy9rx5VKcEVGCiqfWhoqM40eIvgAAAAP5YVJk6cqG/inps6VlIqMFBUpsCT2nedU4+xsbGW86VLl5aYmBh3G28wlREAAD/+4qW0tDRJTU21HAsPD5dgRnAAAIAfhYeH+yQYiI+P1485OTl6toKL2m/UqJG7TW5uruV1RUVFegaD6/XeoKwAAECQzFb4OTVr1tQ3+IyMDPcxNX5BjSVITEzU++rx5MmTkpWV5W6zatUqMQxDj03wFpkDAAD8WFYoCbUewd69ey2DEDdv3qzHDCQkJMiTTz4p48ePl+uvv14HC88++6yegeCa0VCnTh258847pX///nq6Y2FhoQwePFjPZPB2poJCcAAAQJDYtGmTtG3b1r3vGquQkpKipys+9dRTei0EtW6ByhC0atVKT1UsW7as+zVvv/22DgjatWunZyl0795dr41QEqxzAAQx1jkAArPOwe8rN/bZtb45/qX82pA5AAAgSMoKwYIBiQAAwILMAQAANqZpiJMRHAAAYGM4vKxAcAAAgI0ZHGP1A4YxBwAAwILMAQAANgZlBQAA4MmkrAAAAHABmQMAAGwMh2cOCA4AALAxHT7mgLICAACwIHMAAICNSVkBAAB4MigrAAAAXEDmAAAAG5OyAgAA8GQQHAAAAE+mw4MDxhwAAAALMgcAANgYDp+tQHAAAICNSVkBAADgAjIHAADYGA7PHBAcAABgYzp8zAFlBQAAYEHmAAAAG4OyAgAA8GQ6PDigrAAAACzIHAAAYGM6fEAiwQEAADamw8sKBAcAANiYDg8OGHMAAAAsyBwAAGBjirOFmE7PncDi3LlzMnHiRElLS5Pw8PBAdwcICvy9gNMQHMDi1KlTEh0dLXl5eRIVFRXo7gBBgb8XcBrGHAAAAAuCAwAAYEFwAAAALAgOYKEGW40ZM4ZBV4AH/l7AaRiQCAAALMgcAAAAC4IDAABgQXAAAAAsCA4AAIAFwQEAALAgOIDbX//6V6lRo4aULVtWmjdvLhs2bAh0l4CAWrt2rXTu3FmqVasmISEhsmjRokB3CbgiCA6gvfvuu5Kamqrncn/55ZfSsGFDSU5Oltzc3EB3DQiYs2fP6r8LKnAGnIR1DqCpTEGzZs3ktdde0/uGYcg111wjQ4YMkaeffjrQ3QMCTmUOFi5cKF26dAl0VwC/I3MAKSgokKysLElKSnIfCw0N1fuZmZkB7RsA4MojOIAcP35czp8/L3FxcZbjaj87Oztg/QIABAbBAQAAsCA4gFSuXFlKlSolOTk5luNqPz4+PmD9AgAEBsEBpEyZMtKkSRPJyMhwH1MDEtV+YmJiQPsGALjySgfgPRGE1DTGlJQUadq0qdx8880ydepUPY2rb9++ge4aEDBnzpyRvXv3uvf3798vmzdvlpiYGElISAho3wB/Yioj3NQ0xsmTJ+tBiI0aNZJp06bpKY6AU61evVratm170XEVSM+ZMycgfQKuBIIDAABgwZgDAABgQXAAAAAsCA4AAIAFwQEAALAgOAAAABYEBwAAwILgAAAAWBAcAAAAC4IDAABgQXAAAAAsCA4AAIB4+j9wFOdPNYeibwAAAABJRU5ErkJggg==",
      "text/plain": [
       "<Figure size 640x480 with 2 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.metrics import confusion_matrix\n",
    "\n",
    "# Assuming y_test and y_pred are defined earlier in your code\n",
    "sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d')\n",
    "plt.title(\"Confusion Matrix\")\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c124ec2c-d8c0-4aca-8a95-f537824323c4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
